spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/test-45893
          #jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com
      cors:
        allowed-origins:
          - http://localhost:8080
          - http://localhost:4200
        allowed-methods:
          - OPTIONS
          - GET
          - PUT
          - POST
          - PATCH
          - DELETE
        allowed-headers:
          - Accept
          - Authorization
          - Content-Type
          - Access-Control-Allow-Origin
          - Access-Control-Allow-Methods
          - Access-Control-Allow-Headers
          - Access-Control-Expose-Headers
        exposed-headers:
          - Access-Control-Allow-Origin
          - Access-Control-Allow-Headers
          - Access-Control-Expose-Headers
          - Content-Type
          - Authorization
          - Accept
        allow-credentials: true